### PR TITLE
Update to framework 8 and testbench 5.0

### PR DESCRIPTION
**Pull request by rogozinds**
This change is [Reviewable](https://reviewable.io/reviews/vaadin/testbench-demo/5)

### CODE REVIEW

**Comment by johannesh2** [comment]
:lgtm:

---

Review status: 0 of 4 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/testbench-demo/5#-:-Kf6IiITOpqvYEVm6iBh:bnfp4nl)*

**Comment by alvarezguille** [comment]
what about changes for the tests? should TableElement be changed for GridElement?

---

Reviewed 4 of 4 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/testbench-demo/5#-:-Kf702d4uarIoxc8ZLUl:bljftjj)*

**Comment by alvarezguille** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

*[a discussion](https://reviewable.io:443/reviews/vaadin/testbench-demo/5#-Kf70nhBDLlZxoq3t-4S:-Kf70nhCRUxh6R_AGQgG:btxjnpr) (no related file):*
what about changes for the tests? should TableElement be changed for GridElement?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/testbench-demo/5)*

**Comment by rogozinds** [comment]
Review status: 3 of 9 files reviewed at latest revision, 1 unresolved discussion.

---

*[a discussion](https://reviewable.io:443/reviews/vaadin/testbench-demo/5#-Kf70nhBDLlZxoq3t-4S:-KfCCc1v6nRTX6OyjSVE:bb6un1j) (no related file):*
<details><summary><i>Previously, alvarezguille (Guille) wrote…</i></summary><blockquote>

what about changes for the tests? should TableElement be changed for GridElement?
</blockquote></details>

Done

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/testbench-demo/5)*

**Comment by alvarezguille** [comment]
Reviewed 4 of 6 files at r2, 6 of 6 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/testbench-demo/5)*

**Pull request merged**
